### ISSUE TITLE
Spawn

### ISSUE THREAD

**Issue by DutchPatrick** [xognovalis/Adversary-Buildmode#1]
Is there a option to make people spawn with Buildzone on connecting?
Because now everyone spawns in PVP Mode.

**Comment by xognovalis** [comment]
I am currently rewriting Adversary-Buildmode. I will implement this in the new version. I do not have an estimated time that this will be done but it will be soon. For now you can write a hook to make players spawn in buildmode.

```lua
hook.Add("PlayerInitialSpawn", "SetBuildmodeOnSpawn", function(ply)
    ply:SetNWInt("Buildmode", 1)
end)
```

**Comment by DutchPatrick** [comment]
Nice
